config/routes.rb
Blog::Application.routes.draw do

  resources :notifications

  resources :locations

  resources :employers

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  get "sign_up" => "users#new", :as => "sign_up"

  resources :kategorijas

  resources :advartisments

  resources :users

  resources :cvs

  root to: 'main#index'

  resources :posts

  resources :sessions

end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/index.html.erb
<div id="wrapper">

<!-- Sidebar -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Berza poslova</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav side-nav">

        <li>  <a href="/#">  {{'HOME' | translate}} </a> </li>
        <li>  <a href="/#/about">  {{'ABOUT' | translate}} </a> </li>
        <li>  <a href="/#/contact">  {{'CONTACT' | translate}} </a> </li>
        <% if current_user %>
            <li>  <a href="/#/cv/new">  {{'NEWCV' | translate}} </a> </li>

      <%elsif current_employer %>
            <li>  <a href="/#/advartisment/new">  {{'NEWADVARTISMENT' | translate}} </a> </li>
            <li>  <a href="/#/myadvartisment/<%=current_employer.name%>">  Moji oglasi  </a> </li>




      <%else %>
        <%end%>
      </ul>
      <ul class="nav navbar-nav navbar-right navbar-user">
        <% if current_user %>
        <li class="dropdown user-dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <%= current_user.email %> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="#user/<%=current_user.id%>"> Profil </a></li>
            <li><a href="#user/edit/<%=current_user.id%>"> Postavke </a></li>
            <li class="divider"></li>
            <li><a href="#"></i> <%= link_to (t "nav.logout"), log_out_path %></a></li>
          </ul>
        </li>
        <%elsif current_employer %>
            <li class="dropdown user-dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <%= current_employer.email %> <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#employer/<%=current_employer.id%>"> Profil </a></li>
                <li><a href="#employer/edit/<%=current_employer.id%>"> Postavke </a></li>
                <li class="divider"></li>
                <li><a href="#"></i> <%= link_to (t "nav.logout"), log_out_path %></a></li>
              </ul>
            </li>
        <% else%>
            <li class="dropdown user-dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{'REGISTER' | translate}} <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li> <a href="/#/user/new">{{'USER' | translate}}</a></li>
                <li> <a href="/#/employer/new">{{'EMPLOYER' | translate}}</a></li>
              </ul>
            </li>
            <li class="dropdown user-dropdown">
              <%= link_to 'Prijava', log_in_path %>
            </li>
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>

<div id="page-wrapper">








      <div ng-view>      </div>





</div><!-- /#page-wrapper -->

</div><!-- /#wrapper -->

<!-- JavaScript -->